# Generated by Django 5.1.7 on 2025-12-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryboy',
            options={'verbose_name': 'Delivery Boy', 'verbose_name_plural': 'Delivery Boys'},
        ),
        migrations.AlterModelOptions(
            name='deliveryotp',
            options={'verbose_name': 'Delivery OTP', 'verbose_name_plural': 'Delivery OTPs'},
        ),
    ]
