# Generated by Django 5.1 on 2024-08-31 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authcart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
