# Generated by Django 5.1.7 on 2025-12-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyzoneapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='timestamp',
            new_name='update_date',
        ),
        migrations.AlterField(
            model_name='orders',
            name='BookDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='orders',
            name='items_json',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='oid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='paymentstatus',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='update_desc',
            field=models.TextField(),
        ),
    ]
