# Generated by Django 5.1.7 on 2025-12-22 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyzoneapp', '0002_rename_timestamp_orderupdate_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='update', to='buyzoneapp.orders'),
        ),
    ]
