# Generated by Django 5.1.7 on 2025-12-29 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyzoneapp', '0004_alter_orders_options_orders_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderupdate',
            options={'verbose_name': 'Order Update', 'verbose_name_plural': 'Order Updates'},
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update', to='buyzoneapp.orders'),
        ),
    ]
