# Generated by Django 5.1.7 on 2025-12-29 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyzoneapp', '0005_alter_orderupdate_options_alter_orderupdate_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='buyzoneapp.orders'),
        ),
    ]
