# Generated by Django 5.1.7 on 2026-01-05 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyzoneapp', '0007_size_remove_product_availability_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='BookDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'size')},
        ),
    ]
