# Generated by Django 5.1.7 on 2026-01-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyzoneapp', '0008_alter_orders_bookdate_alter_productvariant_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledPaidOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Cancelled & Paid Order',
                'verbose_name_plural': 'Cancelled & Paid Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('buyzoneapp.orders',),
        ),
        migrations.AddField(
            model_name='orders',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='refund_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
