# Generated by Django 5.1.7 on 2026-01-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyzoneapp', '0010_orders_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='razorpay_order_id',
        ),
    ]
