# Generated by Django 5.1.7 on 2026-01-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyzoneapp', '0011_remove_orders_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancelledpaidorder',
            options={'verbose_name': 'Refundable Orders', 'verbose_name_plural': 'Refundable Orders'},
        ),
    ]
