# Generated by Django 5.1.7 on 2026-01-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyzoneapp', '0012_alter_cancelledpaidorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
